aa: null
amp: false
aug_splits: 0
batch_size: 14
bn_eps: null
bn_momentum: null
bn_tf: false
color_jitter: 0.4
cooldown_epochs: 10
crop_pct: null
data: output_dataset
decay_epochs: 30
decay_rate: 0.1
dist_bn: ''
drop: 0.0
drop_block: null
drop_connect: null
drop_path: null
epochs: 200
eval_metric: top1
gp: avg
img_size: null
initial_checkpoint: ''
interpolation: ''
jsd: false
local_rank: 0
log_interval: 50
lr: 0.01
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
mean: null
min_lr: 1.0e-05
mixup: 0.0
mixup_off_epoch: 0
model: efficientnet_b3a
model_ema: false
model_ema_decay: 0.9998
model_ema_force_cpu: false
momentum: 0.9
no_prefetcher: false
no_resume_opt: false
num_classes: 1000
num_gpu: 1
opt: sgd
opt_eps: 1.0e-08
output: ''
patience_epochs: 10
pin_mem: false
pretrained: true
recount: 1
recovery_interval: 10
remode: const
reprob: 0.0
resplit: false
resume: ''
save_images: false
sched: step
seed: 42
smoothing: 0.1
split_bn: false
start_epoch: null
std: null
sync_bn: false
train_interpolation: random
tta: 0
use_multi_epochs_loader: false
validation_batch_size_multiplier: 1
warmup_epochs: 3
warmup_lr: 0.0001
weight_decay: 0.0001
workers: 4
